name: Hola Mundo Java CI

on:
  push:
    branches: [ workflows ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Compilar y ejecutar Hola Mundo
        run: |
          javac src/com/automatization/cicd/HolaMundo.java
          java -cp src com.automatization.cicd.HolaMundo
