name: Hola Mundo Java CI

on:
  push:
    branches: [ main, workflows ]
  pull_request:
    branches: [ main ] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Compilar y ejecutar Hola Mundo
        run: |
          javac src/com/johana/cicd/HolaMundo.java
          java -cp src com.johana.cicd.HolaMundo
